BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `Series` (
	`Id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`Description`	TEXT NOT NULL,
	`Status`	TEXT
);
CREATE TABLE IF NOT EXISTS `Episodes` (
	`Id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`SerieId`	INTEGER,
	`Number`	INTEGER NOT NULL,
	`Season`	INTEGER NOT NULL,
	`Name`	TEXT,
	`Description`	INTEGER,
	`Status`	TEXT,
	FOREIGN KEY(`SerieId`) REFERENCES `Series`(`Id`) ON DELETE CASCADE
);
COMMIT;
